// AUTO-GENERATED by scripts/generate-image-manifest.mjs
// Run `npm run generate-images` to regenerate. Do not edit manually.

import img_0 from "./7_wonders_duel_travel_box_1.jpg";
import img_1 from "./7_wonders_duel_travel_box_2.jpg";
import img_2 from "./7_wonders_duel_travel_box_3.jpg";
import img_3 from "./7_wonders_duel_with_all_expansions_inserts_1.jpg";
import img_4 from "./7_wonders_duel_with_all_expansions_inserts_2.jpg";
import img_5 from "./7_wonders_duel_with_all_expansions_inserts_3.jpg";
import img_6 from "./7_wonders_duel_with_all_expansions_inserts_4.jpg";
import img_7 from "./7_wonders_duel_with_all_expansions_inserts_5.jpg";
import img_8 from "./card_and_resource_tray_1.jpg";
import img_9 from "./card_and_resource_tray_2.jpg";
import img_10 from "./card_and_resource_tray_3.jpg";
import img_11 from "./cascadia_board_game_Insert_1.jpg";
import img_12 from "./cascadia_board_game_Insert_2.jpg";
import img_13 from "./cascadia_board_game_Insert_3.jpg";
import img_14 from "./clank_caatacombs_token_holder_1.jpg";
import img_15 from "./clank_caatacombs_token_holder_2.jpg";
import img_16 from "./clank_caatacombs_token_holder_3.jpg";
import img_17 from "./codenames_travel_box_1.png";
import img_18 from "./codenames_travel_box_2.png";
import img_19 from "./codenames_travel_box_3.png";
import img_20 from "./decrypto_inserts_1.jpg";
import img_21 from "./decrypto_inserts_2.jpg";
import img_22 from "./meeple_shaped_stackable_board_game_resource_tray_1.jpg";
import img_23 from "./meeple_shaped_stackable_board_game_resource_tray_2.jpg";
import img_24 from "./sky_team_inserts_1.jpg";
import img_25 from "./sky_team_inserts_2.jpg";
import img_26 from "./sky_team_inserts_3.jpg";
import img_27 from "./stackable_hexagon_token_tray_1.jpg";
import img_28 from "./stackable_hexagon_token_tray_2.jpg";
import img_29 from "./terraforming_mars_inserts_1.jpg";
import img_30 from "./terraforming_mars_inserts_2.jpg";
import img_31 from "./terraforming_mars_inserts_3.jpg";
import img_32 from "./terraforming_mars_inserts_4.jpg";
import img_33 from "./terraforming_mars_overlay_mats_1.jpg";
import img_34 from "./terraforming_mars_overlay_mats_2.webp";
import img_35 from "./terraforming_mars_overlay_mats_3.jpg";
import img_36 from "./terraforming_mars_overlay_mats_4.jpg";
import img_37 from "./wingspan_food_tokens_1.png";
import img_38 from "./wingspan_food_tokens_2.jpg";
import img_39 from "./wingspan_inserts_1.jpeg";
import img_40 from "./wingspan_inserts_2.jpeg";
import img_41 from "./wingspan_inserts_3.jpeg";
import img_42 from "./wingspan_inserts_4.jpeg";
import img_43 from "./wingspan_inserts_5.jpeg";

type ImageImport = { src: string; width: number; height: number };

const productImages: Record<string, ImageImport[]> = {
  "7_wonders_duel_travel_box": [img_0, img_1, img_2],
  "7_wonders_duel_with_all_expansions_inserts": [img_3, img_4, img_5, img_6, img_7],
  "card_and_resource_tray": [img_8, img_9, img_10],
  "cascadia_board_game_Insert": [img_11, img_12, img_13],
  "clank_caatacombs_token_holder": [img_14, img_15, img_16],
  "codenames_travel_box": [img_17, img_18, img_19],
  "decrypto_inserts": [img_20, img_21],
  "meeple_shaped_stackable_board_game_resource_tray": [img_22, img_23],
  "sky_team_inserts": [img_24, img_25, img_26],
  "stackable_hexagon_token_tray": [img_27, img_28],
  "terraforming_mars_inserts": [img_29, img_30, img_31, img_32],
  "terraforming_mars_overlay_mats": [img_33, img_34, img_35, img_36],
  "wingspan_food_tokens": [img_37, img_38],
  "wingspan_inserts": [img_39, img_40, img_41, img_42, img_43]
};

export default productImages;
