// AUTO-GENERATED by scripts/generate-image-manifest.mjs
// Run `npm run generate-images` to regenerate. Do not edit manually.

import img_0 from "./3_row_playing_card_holder_95gm_1.jpg";
import img_1 from "./3_row_playing_card_holder_95gm_2.jpg";
import img_2 from "./3_row_playing_card_holder_95gm_3.jpg";
import img_3 from "./6_comartment_game_tray_1.jpeg";
import img_4 from "./6_comartment_game_tray_2.jpeg";
import img_5 from "./7_wonders_duel_travel_box_1.jpg";
import img_6 from "./7_wonders_duel_travel_box_2.jpg";
import img_7 from "./7_wonders_duel_travel_box_3.jpg";
import img_8 from "./7_wonders_duel_with_all_expansions_inserts_1.jpg";
import img_9 from "./7_wonders_duel_with_all_expansions_inserts_2.jpg";
import img_10 from "./7_wonders_duel_with_all_expansions_inserts_3.jpg";
import img_11 from "./7_wonders_duel_with_all_expansions_inserts_4.jpg";
import img_12 from "./7_wonders_duel_with_all_expansions_inserts_5.jpg";
import img_13 from "./arc_nova_coins_upgrade_120gm_1.webp";
import img_14 from "./arc_nova_coins_upgrade_120gm_2.webp";
import img_15 from "./arcs_inserts_with_leaders_and_lore_expension_940gms_multicolor_1.webp";
import img_16 from "./arcs_inserts_with_leaders_and_lore_expension_940gms_multicolor_2.webp";
import img_17 from "./bomb_busters_inserts_740gm_1.jpg";
import img_18 from "./bomb_busters_inserts_740gm_2.jpg";
import img_19 from "./bomb_busters_inserts_740gm_3.jpg";
import img_20 from "./bomb_busters_tile_holder_70gm_1.jpg";
import img_21 from "./bomb_busters_tile_holder_70gm_2.jpg";
import img_22 from "./bomb_busters_tile_holder_preminum_130gm_1.jpeg";
import img_23 from "./bomb_busters_tile_holder_preminum_130gm_2.jpeg";
import img_24 from "./bomb_busters_tile_holder_preminum_130gm_3.jpg";
import img_25 from "./brass_birmingham_coins_upgrade_110gm_1.webp";
import img_26 from "./brass_birmingham_coins_upgrade_110gm_2.webp";
import img_27 from "./brass_birmingham_inserts_1.jpg";
import img_28 from "./brass_birmingham_inserts_2.jpg";
import img_29 from "./brass_birmingham_inserts_3.jpg";
import img_30 from "./brass_birmingham_inserts_4.jpg";
import img_31 from "./brass_birmingham_inserts_5.jpg";
import img_32 from "./brass_birmingham_inserts_6.jpg";
import img_33 from "./carcassonne_travel_box_220gm_1.webp";
import img_34 from "./carcassonne_travel_box_220gm_2.jpg";
import img_35 from "./carcassonne_travel_box_220gm_3.jpg";
import img_36 from "./carcassonne_travel_box_220gm_4.webp";
import img_37 from "./carcassonne_travel_box_220gm_5.webp";
import img_38 from "./carcassonnne_meeple_tray_34gm_1.webp";
import img_39 from "./carcassonnne_meeple_tray_34gm_2.webp";
import img_40 from "./card_and_resource_tray_1.jpg";
import img_41 from "./card_and_resource_tray_2.jpg";
import img_42 from "./card_and_resource_tray_3.jpg";
import img_43 from "./card_organizer_cum_draw_tray_62gm_1.jpg";
import img_44 from "./card_organizer_cum_draw_tray_62gm_2.jpg";
import img_45 from "./cards_storage_customizable_boxes_52gm_1.webp";
import img_46 from "./cards_storage_customizable_boxes_52gm_2.webp";
import img_47 from "./cards_storage_customizable_boxes_52gm_3.jpg";
import img_48 from "./cascadia_board_game_Insert_1.jpg";
import img_49 from "./cascadia_board_game_Insert_2.jpg";
import img_50 from "./cascadia_board_game_Insert_3.jpg";
import img_51 from "./castle_dice_150gm_tower_1.jpg";
import img_52 from "./castle_dice_150gm_tower_2.jpg";
import img_53 from "./catan_base_plus_5-6_player_exp_730gm_1.webp";
import img_54 from "./catan_base_plus_5-6_player_exp_730gm_2.jpg";
import img_55 from "./catan_board_organizer_210gm_1.png";
import img_56 from "./catan_cities_and_knights_cards_set_of_2_trays_with_lid_220gm_1.webp";
import img_57 from "./catan_cities_and_knights_cards_set_of_2_trays_with_lid_220gm_2.webp";
import img_58 from "./catan_cities_and_knights_cards_set_of_2_trays_with_lid_220gm_3.webp";
import img_59 from "./catan_cities_and_knights_cards_set_of_2_trays_with_lid_220gm_4.webp";
import img_60 from "./catan_cities_and_knights_cards_set_of_2_trays_with_lid_220gm_5.webp";
import img_61 from "./catan_cities_and_knights_player_meeple_organizer_115gm_1.webp";
import img_62 from "./catan_cities_and_knights_token_holder_with_lid_195gm_1.webp";
import img_63 from "./catapult_dice_tower_385gm_1.jpg";
import img_64 from "./catapult_dice_tower_385gm_2.jpg";
import img_65 from "./catapult_dice_tower_385gm_3.jpg";
import img_66 from "./catapult_dice_tower_385gm_4.jpg";
import img_67 from "./catapult_dice_tower_385gm_5.webp";
import img_68 from "./clank_caatacombs_token_holder_1.jpg";
import img_69 from "./clank_caatacombs_token_holder_2.jpg";
import img_70 from "./clank_caatacombs_token_holder_3.jpg";
import img_71 from "./clank_catacombs_inserts_with_expansion_1450gm_1.webp";
import img_72 from "./clank_catacombs_inserts_with_expansion_1450gm_2.webp";
import img_73 from "./clank_catacombs_inserts_with_expansion_1450gm_3.webp";
import img_74 from "./clank_catacombs_inserts_with_expansion_1450gm_4.webp";
import img_75 from "./clank_catacombs_inserts_with_expansion_1450gm_5.webp";
import img_76 from "./clank_catacombs_inserts_with_expansion_1450gm_6.jpg";
import img_77 from "./clank_catacombs_inserts_with_expansion_1450gm_6.webp";
import img_78 from "./codenames_travel_box_1.png";
import img_79 from "./codenames_travel_box_2.png";
import img_80 from "./codenames_travel_box_3.png";
import img_81 from "./cosmic_encounter_dominion_incursion_inserts_700gm_1.webp";
import img_82 from "./cosmic_encounter_dominion_incursion_inserts_700gm_2.png";
import img_83 from "./cosmic_encounter_dominion_incursion_inserts_700gm_3.png";
import img_84 from "./cosmic_encounter_dominion_incursion_inserts_700gm_4.png";
import img_85 from "./cosmic_encounter_dominion_incursion_inserts_700gm_5.webp";
import img_86 from "./cubitos_with_expensions_inserts_700gm_1.jpg";
import img_87 from "./cubitos_with_expensions_inserts_700gm_2.jpg";
import img_88 from "./cubitos_with_expensions_inserts_700gm_3.jpg";
import img_89 from "./cubitos_with_expensions_inserts_700gm_4.jpg";
import img_90 from "./cubitos_with_expensions_inserts_700gm_5.jpg";
import img_91 from "./cubitos_with_expensions_inserts_700gm_6.jpg";
import img_92 from "./d6_dice_4gm_10mm_to_20mm_size_1.webp";
import img_93 from "./decrypto_inserts_1.jpg";
import img_94 from "./decrypto_inserts_2.jpg";
import img_95 from "./deep_sea_adventure_insert_60gm_1.jpg";
import img_96 from "./deep_sea_adventure_insert_60gm_2.jpg";
import img_97 from "./deep_sea_adventure_insert_60gm_3.jpg";
import img_98 from "./deep_sea_adventure_insert_60gm_4.jpg";
import img_99 from "./DnD_player_character_miniatures_1.webp";
import img_100 from "./double_slot_resource_tray_1.jpg";
import img_101 from "./draw_and_discard_78gm_tray_1.jpg";
import img_102 from "./draw_and_discard_78gm_tray_2.jpg";
import img_103 from "./dune_imperium_base_game_insert_980gm_1.webp";
import img_104 from "./dune_imperium_base_game_insert_980gm_2.webp";
import img_105 from "./Dune_Imperium_uprising_insert_base_game_1200gm_1.webp";
import img_106 from "./Dune_Imperium_uprising_insert_base_game_1200gm_2.webp";
import img_107 from "./Dune_Imperium_uprising_insert_base_game_1200gm_3.webp";
import img_108 from "./Dune_Imperium_uprising_insert_base_game_1200gm_4.webp";
import img_109 from "./Dune_Imperium_uprising_insert_base_game_1200gm_5.webp";
import img_110 from "./dune_war_for_arrakis_insert_with_both_exp_1230g_1.webp";
import img_111 from "./dune_war_for_arrakis_insert_with_both_exp_1230g_2.webp";
import img_112 from "./dune_war_for_arrakis_insert_with_both_exp_1230g_3.webp";
import img_113 from "./dune_war_for_arrakis_insert_with_both_exp_1230g_4.webp";
import img_114 from "./dune_war_for_arrakis_insert_with_both_exp_1230g_5.webp";
import img_115 from "./full_dice_set_kit_Card_DIY_18gm_1.webp";
import img_116 from "./full_dice_set_kit_Card_DIY_18gm_2.webp";
import img_117 from "./full_dice_set_kit_Card_DIY_18gm_3.webp";
import img_118 from "./full_dice_set_kit_Card_DIY_18gm_4.webp";
import img_119 from "./funnel_tray_1.jpg";
import img_120 from "./Gloomhaven_JOTL_player_dashboard_72gm_1.webp";
import img_121 from "./Gloomhaven_JOTL_player_dashboard_72gm_2.webp";
import img_122 from "./Gloomhaven_JOTL_player_dashboard_72gm_3.jpeg";
import img_123 from "./Gloomhaven_JOTL_player_dashboard_72gm_4.jpg";
import img_124 from "./heat_padel_to_the_metal_gearbox_overlay_13gm_1.webp";
import img_125 from "./heat_padel_to_the_metal_gearbox_overlay_13gm_2.webp";
import img_126 from "./heat_padel_to_the_metal_gearbox_overlay_13gm_3.jpg";
import img_127 from "./hex_dice_tray_70gm_1.jpg";
import img_128 from "./hex_dice_tray_70gm_2.jpg";
import img_129 from "./hues_and_cues_scorring_fence_14gm_1.webp";
import img_130 from "./interlocking_resource_trays_24gm_1.jpg";
import img_131 from "./interlocking_resource_trays_24gm_2.jpg";
import img_132 from "./interlocking_resource_trays_24gm_3.jpg";
import img_133 from "./interlocking_resource_trays_24gm_4.jpg";
import img_134 from "./lords_of_waterdeep_skulls_30_pack_140gm_1.png";
import img_135 from "./lords_of_waterdeep_skulls_30_pack_140gm_2.webp";
import img_136 from "./lords_of_waterdeep_skulls_30_pack_140gm_3.webp";
import img_137 from "./lost_ruins_with_all_expensions_1.jpg";
import img_138 from "./lost_ruins_with_all_expensions_2.jpg";
import img_139 from "./lost_ruins_with_all_expensions_3.jpg";
import img_140 from "./lost_ruins_with_all_expensions_4.jpg";
import img_141 from "./meeple_shaped_stackable_board_game_resource_tray_1.jpg";
import img_142 from "./meeple_shaped_stackable_board_game_resource_tray_2.jpg";
import img_143 from "./modular_card_and_resource_tray_with_round_card_holder_225gm_1.webp";
import img_144 from "./modular_card_and_resource_tray_with_round_card_holder_225gm_2.webp";
import img_145 from "./modular_card_and_resource_tray_with_round_card_holder_225gm_3.webp";
import img_146 from "./mountain_goat_meeple_1.png";
import img_147 from "./mountain_goat_meeple_2.webp";
import img_148 from "./mountain_goats_145gm_1.jpg";
import img_149 from "./mountain_tile_2_to_5_cms_7gm_1.webp";
import img_150 from "./old_kings_crown_insert_1200gm_1.jpg";
import img_151 from "./old_kings_crown_insert_1200gm_2.jpg";
import img_152 from "./old_kings_crown_insert_1200gm_3.jpg";
import img_153 from "./old_kings_crown_insert_1200gm_4.jpg";
import img_154 from "./old_kings_crown_insert_1200gm_5.jpg";
import img_155 from "./pandemic_base_game_insert_290gm_1.webp";
import img_156 from "./pandemic_base_game_insert_290gm_2.webp";
import img_157 from "./pandemic_base_game_insert_290gm_3.webp";
import img_158 from "./pandemic_base_game_insert_290gm_4.jpg";
import img_159 from "./pandemic_base_game_insert_290gm_5.jpg";
import img_160 from "./player_score_tracker_45gm_1.jpg";
import img_161 from "./player_score_tracker_45gm_2.jpg";
import img_162 from "./player_score_tracker_45gm_3.jpg";
import img_163 from "./player_score_tracker_45gm_4.jpg";
import img_164 from "./pocket_and_travel_dice_tower_90gm_1.webp";
import img_165 from "./pocket_and_travel_dice_tower_90gm_2.webp";
import img_166 from "./pocket_and_travel_dice_tower_90gm_3.webp";
import img_167 from "./portable_personal_dice_tray_fold_to_close_61gm_1.webp";
import img_168 from "./portable_personal_dice_tray_fold_to_close_61gm_2.webp";
import img_169 from "./portable_personal_dice_tray_fold_to_close_61gm_3.webp";
import img_170 from "./portable_personal_dice_tray_fold_to_close_61gm_4.webp";
import img_171 from "./root_base_game_insert_440gm_1.webp";
import img_172 from "./root_base_game_insert_440gm_2.webp";
import img_173 from "./root_base_game_insert_440gm_3.webp";
import img_174 from "./root_base_game_insert_440gm_4.webp";
import img_175 from "./root_base_game_insert_440gm_5.webp";
import img_176 from "./root_base_game_insert_440gm_6.webp";
import img_177 from "./scout_game_inserts_43gm_1.webp";
import img_178 from "./scout_game_inserts_43gm_2.webp";
import img_179 from "./scout_game_inserts_43gm_3.webp";
import img_180 from "./scrable_tile_holder_10cm_to_16cm_20gm_1.webp";
import img_181 from "./scrable_tile_holder_10cm_to_16cm_20gm_2.webp";
import img_182 from "./single_card_tray_customizable_45gm_1.webp";
import img_183 from "./single_card_tray_customizable_45gm_2.webp";
import img_184 from "./single_card_tray_customizable_45gm_3.webp";
import img_185 from "./single_card_tray_customizable_45gm_4.webp";
import img_186 from "./sky_team_inserts_1.jpg";
import img_187 from "./sky_team_inserts_2.jpg";
import img_188 from "./sky_team_inserts_3.jpg";
import img_189 from "./smash_castle_dice_tower_290gm_1.webp";
import img_190 from "./splendor_base_game_insert_440gm_1.jpg";
import img_191 from "./splendor_base_game_insert_440gm_2.jpg";
import img_192 from "./splendor_base_game_insert_440gm_3.jpg";
import img_193 from "./splendor_travel_case-210gm_1.jpg";
import img_194 from "./splendor_travel_case-210gm_2.jpg";
import img_195 from "./splendor_travel_case-210gm_3.jpg";
import img_196 from "./splendor_travel_case-210gm_4.jpg";
import img_197 from "./stackable_hexagon_token_tray_1.jpg";
import img_198 from "./stackable_hexagon_token_tray_2.jpg";
import img_199 from "./straight_2_cards_slot_holder_40gm_1.jpg";
import img_200 from "./straight_2_cards_slot_holder_40gm_2.jpg";
import img_201 from "./terraforming_mars_inserts_1.jpg";
import img_202 from "./terraforming_mars_inserts_2.jpg";
import img_203 from "./terraforming_mars_inserts_3.jpg";
import img_204 from "./terraforming_mars_inserts_4.jpg";
import img_205 from "./terraforming_mars_overlay_mats_1.jpg";
import img_206 from "./terraforming_mars_overlay_mats_2.webp";
import img_207 from "./terraforming_mars_overlay_mats_3.jpg";
import img_208 from "./terraforming_mars_overlay_mats_4.jpg";
import img_209 from "./ticket_to_ride_premium_train_upgrade_290gm_1.webp";
import img_210 from "./ticket_to_ride_train_tray_19gm_1.webp";
import img_211 from "./ticket_to_ride_train_tray_19gm_2.webp";
import img_212 from "./ticket_to_ride_trains_and_station_organizer_70gm_1.webp";
import img_213 from "./ticket_to_ride_trains_and_station_organizer_70gm_2.webp";
import img_214 from "./ticket_to_ride_trains_and_station_organizer_70gm_3.webp";
import img_215 from "./ticket_to_ride_trains_and_station_organizer_70gm_4.jpeg";
import img_216 from "./ticket_to_ride_trains_storage_65gm_1.webp";
import img_217 from "./ticket_to_ride_trains_storage_65gm_2.webp";
import img_218 from "./ticket_to_ride_trains_storage_65gm_3.webp";
import img_219 from "./ticket_to_ride_trains_storage_65gm_4.jpeg";
import img_220 from "./twilight_imperium_base_game_700gm_inserts_1.jpg";
import img_221 from "./twilight_imperium_base_game_700gm_inserts_2.jpg";
import img_222 from "./twilight_imperium_base_game_700gm_inserts_3.jpg";
import img_223 from "./twilight_imperium_base_game_700gm_inserts_4.jpg";
import img_224 from "./universal_3_slot_card_and_resource_tray_1.jpg";
import img_225 from "./universal_3_slot_card_and_resource_tray_2.jpg";
import img_226 from "./viticulture_insert_with_expension_1.jpg";
import img_227 from "./viticulture_insert_with_expension_2.jpg";
import img_228 from "./wingspan_food_tokens_1.png";
import img_229 from "./wingspan_food_tokens_2.jpg";
import img_230 from "./wingspan_inserts_1.jpeg";
import img_231 from "./wingspan_inserts_2.jpeg";
import img_232 from "./wingspan_inserts_3.jpeg";
import img_233 from "./wingspan_inserts_4.jpeg";
import img_234 from "./wingspan_inserts_5.jpeg";
import img_235 from "./wingspan_travel_box_445gm_1.webp";
import img_236 from "./wingspan_travel_box_445gm_2.webp";
import img_237 from "./wingspan_travel_box_445gm_3.webp";
import img_238 from "./wingspan_travel_box_445gm_4.webp";
import img_239 from "./wingspan_travel_box_445gm_5.webp";
import img_240 from "./wingspan_travel_box_445gm_6.webp";

type ImageImport = { src: string; width: number; height: number };

const productImages: Record<string, ImageImport[]> = {
  "3_row_playing_card_holder_95gm": [img_0, img_1, img_2],
  "6_comartment_game_tray": [img_3, img_4],
  "7_wonders_duel_travel_box": [img_5, img_6, img_7],
  "7_wonders_duel_with_all_expansions_inserts": [img_8, img_9, img_10, img_11, img_12],
  "arc_nova_coins_upgrade_120gm": [img_13, img_14],
  "arcs_inserts_with_leaders_and_lore_expension_940gms_multicolor": [img_15, img_16],
  "bomb_busters_inserts_740gm": [img_17, img_18, img_19],
  "bomb_busters_tile_holder_70gm": [img_20, img_21],
  "bomb_busters_tile_holder_preminum_130gm": [img_22, img_23, img_24],
  "brass_birmingham_coins_upgrade_110gm": [img_25, img_26],
  "brass_birmingham_inserts": [img_27, img_28, img_29, img_30, img_31, img_32],
  "carcassonne_travel_box_220gm": [img_33, img_34, img_35, img_36, img_37],
  "carcassonnne_meeple_tray_34gm": [img_38, img_39],
  "card_and_resource_tray": [img_40, img_41, img_42],
  "card_organizer_cum_draw_tray_62gm": [img_43, img_44],
  "cards_storage_customizable_boxes_52gm": [img_45, img_46, img_47],
  "cascadia_board_game_Insert": [img_48, img_49, img_50],
  "castle_dice_150gm_tower": [img_51, img_52],
  "catan_base_plus_5-6_player_exp_730gm": [img_53, img_54],
  "catan_board_organizer_210gm": [img_55],
  "catan_cities_and_knights_cards_set_of_2_trays_with_lid_220gm": [img_56, img_57, img_58, img_59, img_60],
  "catan_cities_and_knights_player_meeple_organizer_115gm": [img_61],
  "catan_cities_and_knights_token_holder_with_lid_195gm": [img_62],
  "catapult_dice_tower_385gm": [img_63, img_64, img_65, img_66, img_67],
  "clank_caatacombs_token_holder": [img_68, img_69, img_70],
  "clank_catacombs_inserts_with_expansion_1450gm": [img_71, img_72, img_73, img_74, img_75, img_76, img_77],
  "codenames_travel_box": [img_78, img_79, img_80],
  "cosmic_encounter_dominion_incursion_inserts_700gm": [img_81, img_82, img_83, img_84, img_85],
  "cubitos_with_expensions_inserts_700gm": [img_86, img_87, img_88, img_89, img_90, img_91],
  "d6_dice_4gm_10mm_to_20mm_size": [img_92],
  "decrypto_inserts": [img_93, img_94],
  "deep_sea_adventure_insert_60gm": [img_95, img_96, img_97, img_98],
  "DnD_player_character_miniatures": [img_99],
  "double_slot_resource_tray": [img_100],
  "draw_and_discard_78gm_tray": [img_101, img_102],
  "dune_imperium_base_game_insert_980gm": [img_103, img_104],
  "Dune_Imperium_uprising_insert_base_game_1200gm": [img_105, img_106, img_107, img_108, img_109],
  "dune_war_for_arrakis_insert_with_both_exp_1230g": [img_110, img_111, img_112, img_113, img_114],
  "full_dice_set_kit_Card_DIY_18gm": [img_115, img_116, img_117, img_118],
  "funnel_tray": [img_119],
  "Gloomhaven_JOTL_player_dashboard_72gm": [img_120, img_121, img_122, img_123],
  "heat_padel_to_the_metal_gearbox_overlay_13gm": [img_124, img_125, img_126],
  "hex_dice_tray_70gm": [img_127, img_128],
  "hues_and_cues_scorring_fence_14gm": [img_129],
  "interlocking_resource_trays_24gm": [img_130, img_131, img_132, img_133],
  "lords_of_waterdeep_skulls_30_pack_140gm": [img_134, img_135, img_136],
  "lost_ruins_with_all_expensions": [img_137, img_138, img_139, img_140],
  "meeple_shaped_stackable_board_game_resource_tray": [img_141, img_142],
  "modular_card_and_resource_tray_with_round_card_holder_225gm": [img_143, img_144, img_145],
  "mountain_goat_meeple": [img_146, img_147],
  "mountain_goats_145gm": [img_148],
  "mountain_tile_2_to_5_cms_7gm": [img_149],
  "old_kings_crown_insert_1200gm": [img_150, img_151, img_152, img_153, img_154],
  "pandemic_base_game_insert_290gm": [img_155, img_156, img_157, img_158, img_159],
  "player_score_tracker_45gm": [img_160, img_161, img_162, img_163],
  "pocket_and_travel_dice_tower_90gm": [img_164, img_165, img_166],
  "portable_personal_dice_tray_fold_to_close_61gm": [img_167, img_168, img_169, img_170],
  "root_base_game_insert_440gm": [img_171, img_172, img_173, img_174, img_175, img_176],
  "scout_game_inserts_43gm": [img_177, img_178, img_179],
  "scrable_tile_holder_10cm_to_16cm_20gm": [img_180, img_181],
  "single_card_tray_customizable_45gm": [img_182, img_183, img_184, img_185],
  "sky_team_inserts": [img_186, img_187, img_188],
  "smash_castle_dice_tower_290gm": [img_189],
  "splendor_base_game_insert_440gm": [img_190, img_191, img_192],
  "splendor_travel_case-210gm": [img_193, img_194, img_195, img_196],
  "stackable_hexagon_token_tray": [img_197, img_198],
  "straight_2_cards_slot_holder_40gm": [img_199, img_200],
  "terraforming_mars_inserts": [img_201, img_202, img_203, img_204],
  "terraforming_mars_overlay_mats": [img_205, img_206, img_207, img_208],
  "ticket_to_ride_premium_train_upgrade_290gm": [img_209],
  "ticket_to_ride_train_tray_19gm": [img_210, img_211],
  "ticket_to_ride_trains_and_station_organizer_70gm": [img_212, img_213, img_214, img_215],
  "ticket_to_ride_trains_storage_65gm": [img_216, img_217, img_218, img_219],
  "twilight_imperium_base_game_700gm_inserts": [img_220, img_221, img_222, img_223],
  "universal_3_slot_card_and_resource_tray": [img_224, img_225],
  "viticulture_insert_with_expension": [img_226, img_227],
  "wingspan_food_tokens": [img_228, img_229],
  "wingspan_inserts": [img_230, img_231, img_232, img_233, img_234],
  "wingspan_travel_box_445gm": [img_235, img_236, img_237, img_238, img_239, img_240]
};

export default productImages;
